# Generated by Django 3.0.2 on 2020-02-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('version', models.CharField(max_length=50)),
                ('affected_products', models.CharField(max_length=200)),
                ('base_cvss_score', models.IntegerField(default=0)),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('last_modified_date', models.DateTimeField(verbose_name='date last modified')),
            ],
        ),
    ]
