# Generated by Django 3.0.2 on 2020-02-07 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvdapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_data_type', models.CharField(max_length=50)),
                ('cve_data_format', models.CharField(max_length=50)),
                ('cve_data_version', models.CharField(max_length=50)),
                ('cve_data_numberOfCVEs', models.CharField(max_length=50)),
                ('cve_data_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CPE_BASE_METRICV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=50)),
                ('acInsufInfo', models.BooleanField()),
                ('obtainAllPrivilege', models.BooleanField()),
                ('obtainUserPrivilege', models.BooleanField()),
                ('obtainOtherPrivilege', models.BooleanField()),
                ('userInteractionRequired', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CPE_CONFIGURATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_dataversion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CPE_IMPACT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseMetricV2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nvdapp.CPE_BASE_METRICV2')),
            ],
        ),
        migrations.CreateModel(
            name='CPE_MATCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerable', models.BooleanField()),
                ('cpe_22uri', models.CharField(blank=True, default='', max_length=50)),
                ('cpe_23uri', models.CharField(max_length=50)),
                ('versionStartExcluding', models.CharField(blank=True, default='', max_length=50)),
                ('versionStartIncluding', models.CharField(blank=True, default='', max_length=50)),
                ('versionEndExcluding', models.CharField(blank=True, default='', max_length=50)),
                ('versionEndIncluding', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CPE_NAME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpe_22uri', models.CharField(blank=True, default='', max_length=50)),
                ('cpe_23uri', models.CharField(max_length=50)),
                ('last_modified_date', models.DateTimeField(verbose_name='date last modified')),
            ],
        ),
        migrations.CreateModel(
            name='CPE_NODE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=50)),
                ('negate', models.BooleanField()),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nvdapp.CPE_NODE')),
                ('cpe_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nvdapp.CPE_MATCH')),
            ],
        ),
        migrations.CreateModel(
            name='CPE_SUBSCORE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.IntegerField(default=0)),
                ('maximum', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='CVE_ITEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(blank=True, default='', verbose_name='date published')),
                ('last_modified_date', models.DateTimeField(blank=True, default='', verbose_name='date last modified')),
                ('configurations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nvdapp.CPE_CONFIGURATION')),
                ('impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nvdapp.CPE_IMPACT')),
            ],
        ),
        migrations.DeleteModel(
            name='CVE',
        ),
        migrations.AddField(
            model_name='cpe_match',
            name='cpe_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nvdapp.CPE_NAME'),
        ),
        migrations.AddField(
            model_name='cpe_impact',
            name='baseMetricV3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nvdapp.CPE_SUBSCORE'),
        ),
        migrations.AddField(
            model_name='cpe_configuration',
            name='nodes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nvdapp.CPE_NODE'),
        ),
        migrations.AddField(
            model_name='cpe_base_metricv2',
            name='exploitabilityScore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_subscore', to='nvdapp.CPE_SUBSCORE'),
        ),
        migrations.AddField(
            model_name='cpe_base_metricv2',
            name='impactScore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_subscore', to='nvdapp.CPE_SUBSCORE'),
        ),
        migrations.AddField(
            model_name='cpe',
            name='cve_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nvdapp.CVE_ITEM'),
        ),
    ]
