# Generated by Django 3.0.2 on 2020-02-09 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvdapp', '0002_auto_20200207_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPE_BASE_METRICV3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvssv3_version', models.CharField(max_length=5)),
                ('vectorString', models.CharField(max_length=50)),
                ('attackVector', models.CharField(max_length=10)),
                ('attackComplexity', models.CharField(max_length=10)),
                ('privilegesRequired', models.CharField(max_length=10)),
                ('userInteraction', models.CharField(max_length=10)),
                ('scope', models.CharField(max_length=10)),
                ('confidentialityImpact', models.CharField(max_length=10)),
                ('integrityImpact', models.CharField(max_length=10)),
                ('availabilityImpact', models.CharField(max_length=10)),
                ('baseScore', models.IntegerField()),
                ('baseSeverity', models.CharField(max_length=10)),
                ('exploitabilityScore', models.IntegerField(default=0)),
                ('impactScore', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='cpe',
            name='cve_item',
        ),
        migrations.RemoveField(
            model_name='cpe_match',
            name='cpe_22uri',
        ),
        migrations.RemoveField(
            model_name='cpe_match',
            name='cpe_23uri',
        ),
        migrations.AddField(
            model_name='cpe',
            name='cve_items',
            field=models.ManyToManyField(to='nvdapp.CVE_ITEM'),
        ),
        migrations.AddField(
            model_name='cpe_base_metricv2',
            name='accessComplexity',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cpe_base_metricv2',
            name='accessVector',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cpe_base_metricv2',
            name='authentication',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cpe_base_metricv2',
            name='availabilityImpact',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cpe_base_metricv2',
            name='baseScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpe_base_metricv2',
            name='confidentialityImpact',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cpe_base_metricv2',
            name='cvssv2_version',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='cpe_base_metricv2',
            name='integrityImpact',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cpe_base_metricv2',
            name='vectorString',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cve_item',
            name='cve',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cpe',
            name='cve_data_numberOfCVEs',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cpe',
            name='cve_data_timestamp',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='cpe_base_metricv2',
            name='exploitabilityScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cpe_base_metricv2',
            name='impactScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cpe_base_metricv2',
            name='severity',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cpe_configuration',
            name='cve_dataversion',
            field=models.CharField(max_length=5),
        ),
        migrations.RemoveField(
            model_name='cpe_configuration',
            name='nodes',
        ),
        migrations.AddField(
            model_name='cpe_configuration',
            name='nodes',
            field=models.ManyToManyField(to='nvdapp.CPE_NODE'),
        ),
        migrations.RemoveField(
            model_name='cpe_match',
            name='cpe_name',
        ),
        migrations.AddField(
            model_name='cpe_match',
            name='cpe_name',
            field=models.ManyToManyField(to='nvdapp.CPE_NAME'),
        ),
        migrations.AlterField(
            model_name='cpe_match',
            name='versionEndExcluding',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cpe_match',
            name='versionEndIncluding',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cpe_match',
            name='versionStartExcluding',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cpe_match',
            name='versionStartIncluding',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cpe_name',
            name='last_modified_date',
            field=models.DateTimeField(blank=True, verbose_name='date last modified'),
        ),
        migrations.RemoveField(
            model_name='cpe_node',
            name='children',
        ),
        migrations.AddField(
            model_name='cpe_node',
            name='children',
            field=models.ManyToManyField(related_name='_cpe_node_children_+', to='nvdapp.CPE_NODE'),
        ),
        migrations.RemoveField(
            model_name='cpe_node',
            name='cpe_match',
        ),
        migrations.AddField(
            model_name='cpe_node',
            name='cpe_match',
            field=models.ManyToManyField(to='nvdapp.CPE_MATCH'),
        ),
        migrations.AlterField(
            model_name='cpe_node',
            name='negate',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='cpe_node',
            name='operator',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='cpe_impact',
            name='baseMetricV3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nvdapp.CPE_BASE_METRICV3'),
        ),
        migrations.DeleteModel(
            name='CPE_SUBSCORE',
        ),
    ]
